### ISSUE TITLE
AZs are hardcoded in aws-infrastructure/modules/kad-vpc/subnets.vf

### ISSUE THREAD

**Issue by tmcgrath** [maikelpenz/kafka-aws-deployment#3]
Was hoping to try this out, because it looks awesome.  Thought you might want to know, the AZs are hardcoded in  aws-infrastructure/modules/kad-vpc/subnets.vf 

Not a big deal, I can change to us-east-2 equivalents, but thought you'd like to know.

**Comment by maikelpenz** [comment]
Hey @tmcgrath ! 
Good catch. Thanks for creating this issue.
I have just merged the fix for it.
